spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shopsystem?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345678
  thymeleaf:
    cache: false
  redis:
    #     windows
    #     host: 127.0.0.1
    #     Linux
    host: 192.168.254.101
    port: 6379
    jedis:
      pool:
        max-active: 30
        max-idle: 10
        min-idle: 3
        max-wait: 3000