spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shopsystem?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345678