spring:
  #配置数据源
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/shopsystem?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345678
  #注意redis配置写在spring下
  redis:
    #     windows
    #     host: 127.0.0.1
    #     Linux
    host: 192.168.254.101
    port: 6379
    jedis:
      pool:
        max-active: 30
        max-idle: 10
        min-idle: 3
        max-wait: 3000
  #thymeleaf是spring下的配置
  thymeleaf:
    cache: false
  #邮件授权配置
  mail:
    host: smtp.qq.com
    username: xuanyuanmoli@qq.com  #用你自己的
    password: wufarktkfxezihfe   # 用你自己的  邮箱授权码
    default-encoding: utf-8
    port: 465
    properties:
      mail:
        debug: true
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
  #RabbitMQ实现邮件异步传输 配置
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
#mybatis—plus与spring是并列的关系
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.yjx
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
